# Simple Data Collection Configuration
data_collection:
  method: "curated"          # Using curated sample dataset
  source: "manual"           # Manually created examples
  
  # Dataset info
  examples_count: 15         # Total number of examples
  data_format: "json"        # Storage format
  
# Dataset paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  datasets: "data/datasets"

# Data quality settings (what we actually have)
quality:
  min_function_lines: 2        # Minimum lines in function
  max_function_lines: 20       # Maximum lines in function  
  min_comment_words: 5         # Minimum words in comment
  max_comment_words: 25        # Maximum words in comment
  
# File settings
output:
  primary_file: "code_comments_dataset.json"
  backup_format: "csv"
  summary_file: "dataset_summary.json"

# Metadata
metadata:
  collection_date: "2024"
  data_type: "function_comment_pairs" 
  language: "python"
  domain: "general_programming"